(function($) {
  $(document).ready(function() {



$('#numberofwordsidput').text($.trim($('#putContent').text()).split(' ').length);
$('#numberofcharidput').text($.trim($('#putContent').text()).length);
$('#putContent').text($.trim($('#putContent').text()).toLowerCase());
            
        $('#getnewcontent').click(function() {
var raNum=(Math.floor(Math.random()*3+1));
  var raNumText="";
  
  switch(raNum){
    case 1:
            $('#putContent').text("");
            $('#putContent').text("WordPress is an open source Content Management System (CMS), which allows the users to build dynamic websites and blogs. Wordpress is the most popular blogging system on the web and allows updating, customizing and managing the website from its back-end CMS and components.The Content Management System (CMS) is a software which stores all the data such as text, photos, music, documents, etc. and is made available on your website. It helps in editing, publishing and modifying the content of the website.");
            $('#putContent').text($.trim($('#putContent').text()).toLowerCase());
            break;
     case 2:
            $('#putContent').text("");
            $('#putContent').text("Cascading Style Sheets, fondly referred to as CSS, is a simple design language intendedto simplify the process of making web pages presentable.CSS handles the look and feel part of a web page. Using CSS, you can control the colorof the text, the style of fonts, the spacing between paragraphs, how columns are sizedand laid out, what background images or colors are used, as well as a variety of othereffects.CSS is easy to learn and understand but it provides a powerful control over the presentation of an HTML document. Most commonly, CSS is combined with the markup languages HTML or XHTML.");
            $('#putContent').text($.trim($('#putContent').text()).toLowerCase());
            break;
     case 3:
            $('#putContent').text("");
            $('#putContent').text("Originally, HTML was developed with the intent of defining the structure of documents like headings, paragraphs, lists, and so forth to facilitate the sharing of scientific information between researchers. Now, HTML is being widely used to format web pages with the help of different tagsvailable in HTML language");
            $('#putContent').text($.trim($('#putContent').text()).toLowerCase());
            break;
   case 4:
            $('#putContent').text("");
            $('#putContent').text("Javascript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose mplementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities. JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name iveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.");
            $('#putContent').text($.trim($('#putContent').text()).toLowerCase());
            break;  
            default:
           $('#putContent').text("");
            $('#putContent').text("It is an interpreted programming language with object-oriented capabilities. JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java");                 
  			$('#putContent').text($.trim($('#putContent').text()).toLowerCase());
            
  }

$('#numberofwordsidput').text($.trim($('#putContent').text()).split(' ').length);
$('#numberofcharidput').text($.trim($('#putContent').text()).length);
$('#numberoferror').text(parseInt(0));
$('#valForCheck').val(parseInt(0));
$('#texttype').val('');
  });


/*$('#texttype').keyup(function(){
  var getContentForCheck=$.trim($('#putContent').text());
  var gettextareContentForCheck=$('#texttype').val();
  var gettextarevalForCheck=parseInt($.trim($('#valForCheck').val()));
  if(parseInt(gettextareContentForCheck.length)==0){
$('#numberoferror').text(parseInt(0));
$('#valForCheck').val(parseInt(0));
  }else{

//alert(getContentForCheck[gettextarevalForCheck] +" "+gettextareContentForCheck[gettextarevalForCheck]+" -"+getContentForCheck[gettextarevalForCheck].localeCompare(gettextareContentForCheck[gettextarevalForCheck])+"- "+gettextarevalForCheck);

/*if(getContentForCheck[gettextarevalForCheck]!==gettextareContentForCheck[gettextarevalForCheck]){
 var errornumber= parseInt($.trim($('#numberoferror').text()));
$('#numberoferror').text(parseInt(errornumber+1)); 
}*/
/*
if(getContentForCheck[gettextarevalForCheck].localeCompare(gettextareContentForCheck[gettextarevalForCheck])){
	 var errornumber= parseInt($.trim($('#numberoferror').text()));
$('#numberoferror').text(parseInt(errornumber+1)); 
}
$('#valForCheck').val(parseInt(gettextarevalForCheck+1));
}
});*/






$(document).keypress(function(e){

 var getContentForCheck=$.trim($('#putContent').text());
  var gettextareContentForCheck=$('#texttype').val();
  var gettextarevalForCheck=parseInt($.trim($('#valForCheck').val()));
  if(parseInt(gettextareContentForCheck.length)==0){
$('#numberoferror').text(parseInt(0));
$('#valForCheck').val(parseInt(0));
  }else{

if(e.which==8){
  	$('#valForCheck').val(parseInt(gettextarevalForCheck-1));
  	return;	
  	}

if(getContentForCheck[gettextarevalForCheck].localeCompare(gettextareContentForCheck[gettextarevalForCheck])){
	 var errornumber= parseInt($.trim($('#numberoferror').text()));
$('#numberoferror').text(parseInt(errornumber+1)); 
}
$('#valForCheck').val(parseInt(gettextarevalForCheck+1));

}

});








  });
    })(jQuery);
